android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx2048m
org.gradle.parallel=true
org.gradle.caching=true
kotlin.compiler.execution.strategy=in-process
android.experimental.runLintInProcess=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
